# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Starting Machine Learning
email: manab.chetia@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog, I will share my experiences in Machine Learning, Deep Learning and Algorithms as a beginner.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  manmax31
linkedin_username: manabchetia

# Build settings
markdown: kramdown


